import {
	Air,
	AutoMode,
	Bolt,
	Cloud,
	Compress,
	GasMeter,
	LocalGasStation,
	Percent,
	Scale,
	Speed,
	type SvgIconComponent,
	TaxiAlert,
	Thermostat,
	Timer,
	WaterDrop,
	WindPower,
} from "@mui/icons-material";

export const UNITS = {
	distance: "km",
	speed: "km/h",
	rpm: "rpm",
	engine_load: "%",
	throttle_pos: "%",
	maf: "g/s",
	map: "kPa",
	short_fuel_trim_1: "%",
	long_fuel_trim_1: "%",
	short_fuel_trim_2: "%",
	long_fuel_trim_2: "%",
	o2_b1s1: "V",
	o2_b1s2: "V",
	o2_b2s1: "V",
	o2_b2s2: "V",
	timing_advance: "°",
	run_time: "s",
	coolant_temp: "°C",
	intake_temp: "°C",
	ambient_air_temp: "°C",
	control_module_voltage: "V",
	fuel_level: "%",
	barometric_pressure: "kPa",
	distance_w_mil: "km",
	// distance is in some stats but not live samples, that's why it's separate
} as const satisfies Record<Metric | "distance", string>;

export const METRICS = [
	"rpm",
	"speed",
	"engine_load",
	"throttle_pos",
	"maf",
	"map",
	"short_fuel_trim_1",
	"long_fuel_trim_1",
	"short_fuel_trim_2",
	"long_fuel_trim_2",
	"o2_b1s1",
	"o2_b1s2",
	"o2_b2s1",
	"o2_b2s2",
	"timing_advance",
	"run_time",
	"coolant_temp",
	"intake_temp",
	"ambient_air_temp",
	"control_module_voltage",
	"fuel_level",
	"barometric_pressure",
	"distance_w_mil",
] as const;

export const METRICS_LABELS = {
	rpm: "RPM",
	speed: "Speed",
	engine_load: "Engine load",
	throttle_pos: "Throttle position",
	maf: "Mass air flow",
	map: "Manifold pressure",
	short_fuel_trim_1: "Short-term fuel trim 1",
	long_fuel_trim_1: "Long-term fuel trim 1",
	short_fuel_trim_2: "Short-term fuel trim 2",
	long_fuel_trim_2: "Long-term fuel trim 2",
	o2_b1s1: "O₂ bank 1 sensor 1",
	o2_b1s2: "O₂ bank 1 sensor 2",
	o2_b2s1: "O₂ bank 2 sensor 1",
	o2_b2s2: "O₂ bank 2 sensor 2",
	timing_advance: "Ignition timing",
	run_time: "Engine run time",
	coolant_temp: "Coolant temperature",
	intake_temp: "Intake temperature",
	ambient_air_temp: "Ambient temperature",
	control_module_voltage: "ECU voltage",
	fuel_level: "Fuel level",
	barometric_pressure: "Barometric pressure",
	distance_w_mil: "Distance with MIL on",
} as const satisfies Record<Metric, string>;

export const METRIC_ICONS = {
	rpm: Speed,
	speed: Speed,
	engine_load: Scale,
	throttle_pos: Percent,
	run_time: Timer,
	maf: WindPower,
	map: Compress,
	barometric_pressure: Cloud,
	fuel_level: LocalGasStation,
	short_fuel_trim_1: GasMeter,
	long_fuel_trim_1: GasMeter,
	short_fuel_trim_2: GasMeter,
	long_fuel_trim_2: GasMeter,
	o2_b1s1: Air,
	o2_b1s2: Air,
	o2_b2s1: Air,
	o2_b2s2: Air,
	coolant_temp: WaterDrop,
	intake_temp: Thermostat,
	ambient_air_temp: Thermostat,
	timing_advance: AutoMode,
	control_module_voltage: Bolt,
	distance_w_mil: TaxiAlert,
} as const satisfies Record<Metric, SvgIconComponent>;

export const DEFAULT_ENABLED_METRICS = new Set<Metric>([
	"speed",
	"rpm",
	"engine_load",
	"throttle_pos",
	"coolant_temp",
	"map",
]);

export type Metric = (typeof METRICS)[number];
