export const UNITS = {
	distance: "km",
	speed: "km/h",
	rpm: "rpm",
	engine_load: "%",
	throttle_pos: "%",
	maf: "g/s",
	map: "kPa",
	short_fuel_trim_1: "%",
	long_fuel_trim_1: "%",
	short_fuel_trim_2: "%",
	long_fuel_trim_2: "%",
	o2_b1s1: "V",
	o2_b1s2: "V",
	o2_b2s1: "V",
	o2_b2s2: "V",
	timing_advance: "°",
	run_time: "s",
	coolant_temp: "°C",
	intake_temp: "°C",
	ambient_air_temp: "°C",
	control_module_voltage: "V",
	fuel_level: "%",
	barometric_pressure: "kPa",
	distance_w_mil: "km",
	// distance is in some stats but not live samples, that's why it's separate
} satisfies Record<Metric | "distance", string>;

export const METRICS = [
	"rpm",
	"speed",
	"engine_load",
	"throttle_pos",
	"maf",
	"map",
	"short_fuel_trim_1",
	"long_fuel_trim_1",
	"short_fuel_trim_2",
	"long_fuel_trim_2",
	"o2_b1s1",
	"o2_b1s2",
	"o2_b2s1",
	"o2_b2s2",
	"timing_advance",
	"run_time",
	"coolant_temp",
	"intake_temp",
	"ambient_air_temp",
	"control_module_voltage",
	"fuel_level",
	"barometric_pressure",
	"distance_w_mil",
] as const;

export type Metric = (typeof METRICS)[number];
