import {
	AccessTime,
	Air,
	Bolt,
	Cloud,
	Co2,
	Compress,
	GasMeter,
	History,
	LocalGasStation,
	Percent,
	Scale,
	Speed,
	type SvgIconComponent,
	TaxiAlert,
	Thermostat,
	WaterDrop,
} from "@mui/icons-material";

export const UNITS = {
	distance: "km",
	speed: "km/h",
	rpm: "rpm",
	engine_load: "%",
	throttle_pos: "%",
	maf: "g/s",
	map: "kPa",
	short_fuel_trim_1: "%",
	long_fuel_trim_1: "%",
	short_fuel_trim_2: "%",
	long_fuel_trim_2: "%",
	o2_b1s1: "V",
	o2_b1s2: "V",
	o2_b2s1: "V",
	o2_b2s2: "V",
	timing_advance: "°",
	run_time: "s",
	coolant_temp: "°C",
	intake_temp: "°C",
	ambient_air_temp: "°C",
	control_module_voltage: "V",
	fuel_level: "%",
	barometric_pressure: "kPa",
	distance_w_mil: "km",
	// distance is in some stats but not live samples, that's why it's separate
} satisfies Record<Metric | "distance", string>;

export const METRICS = [
	"rpm",
	"speed",
	"engine_load",
	"throttle_pos",
	"maf",
	"map",
	"short_fuel_trim_1",
	"long_fuel_trim_1",
	"short_fuel_trim_2",
	"long_fuel_trim_2",
	"o2_b1s1",
	"o2_b1s2",
	"o2_b2s1",
	"o2_b2s2",
	"timing_advance",
	"run_time",
	"coolant_temp",
	"intake_temp",
	"ambient_air_temp",
	"control_module_voltage",
	"fuel_level",
	"barometric_pressure",
	"distance_w_mil",
] as const;

export const METRIC_ICONS = {
	rpm: Speed,
	speed: Speed,
	engine_load: Scale,
	throttle_pos: Percent,
	run_time: AccessTime,
	maf: Air,
	map: Compress,
	barometric_pressure: Cloud,
	fuel_level: LocalGasStation,
	short_fuel_trim_1: GasMeter,
	long_fuel_trim_1: GasMeter,
	short_fuel_trim_2: GasMeter,
	long_fuel_trim_2: GasMeter,
	o2_b1s1: Co2,
	o2_b1s2: Co2,
	o2_b2s1: Co2,
	o2_b2s2: Co2,
	coolant_temp: WaterDrop,
	intake_temp: Thermostat,
	ambient_air_temp: Thermostat,
	timing_advance: History,
	control_module_voltage: Bolt,
	distance_w_mil: TaxiAlert,
} satisfies Record<Metric, SvgIconComponent>;

export type Metric = (typeof METRICS)[number];
