name: test-on-dev

on: 
  push:
    branches:
      - 'dev'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cd into backend
        run:  cd backend
      - name: test
        run:  ./run_test.sh 
